### ISSUE TITLE
[Question] App launcher activities

### ISSUE THREAD

**Issue by xphnx** [cyngn/android_packages_themes_Template#5]
Hi,
I am trying to edit the template, but I encounter a problem: When editing the file appfilter.xml dont know where to find the various app launcher activities. It could be enough to put just the app package name, as you describe in the example? Is there any way to get the names of the activities? What does the phrase: "if your custom icon shows up in places it shouldnt" means?

![687474703a2f2f63646e2e63796e676e2e636f6d2f672f7468656d65735f74656d706c6174655f696e737472756374696f6e732f6e616d655f776974685f636172652e706e67](https://cloud.githubusercontent.com/assets/4024412/6029163/02ed525a-abef-11e4-80c8-0c43f6083e83.png)

Thanks in advance

**Comment by djdarkknight96** [comment]
Look in the manifest for the activity with the icon name, or search the playstore for the pack that takes requests but just don't send it...open it abd you'll have them all from your device not included in that pack. Otherwise use that packs app filter lines. 

Here's a huge one I use https://www.dropbox.com/s/uo67ag6e0zvk15g/appfilter.xml?dl=1 

Have fun
